apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: stateful-set-mysql
spec:
  serviceName: db
  template:
    metadata:
      labels:
        name: aplicacao-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.5
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "1"
          - name: MYSQL_DATABASE
            value: "loja"
          - name: MYSQL_USER
            value: "root"
          volumeMounts:
          - name: pvc
            mountPath: /var/lib/mysql
      volumes:
       - name: pvc
         persistentVolumeClaim:
           claimName: volume-pvc
